syntax = 'Lua51'
indent_type = "Spaces"
indent_width = 2
column_width = 108
quote_style = 'AutoPreferSingle'
call_parentheses = 'Always'
space_after_function_names = 'Never'
block_newline_gaps = 'Preserve'
collapse_simple_statement = 'ConditionalOnly'


[sort_requires]
enabled = true
