-- This file defines the type system for my over-engineered neovim
-- initialization
--
---@meta
--
--
-- Options definitions -------------------------------------------------------
--
---@class ManagerOptions
---@field public install table The path to where the manager module is installed
---@field public target string The path to where packages are installed
---@field public source table The list of packages that the manager will install/configure
---@field public setup table settings for package configuration

---@class ProfileOptions
---@field public name string The plain name of the profile
---@field public before string[] Options for the "before" phase
---@field public setup string[] Options for the "setup" phase
---@field public after string[] Options for the "after" phase
---@field public managers ManagerOptions[] Options for the managers used in this profile

--  -------------------------------------------------------------
--
---@class Manager
---@field public name string Name used to identify the manager type
---@field private options ManagerOptions The configuration options needed by Manager

---@class Configuration
---@field private name string The plain name of the configuration
---@field private stages string[] The order that configuration should be applied
---@field private managers Manager[] The active managers in the configuration
---@field public profile ProfileOptions the configuration profile to load

-- local Config = require('config')
-- Config = Config:new({profile = 'default'})
--
-- local result = Config:apply()
-- if result then vim.notify(result) end
--
-- profile.default -----
-- {
--   name = 'default',
--   before = { ... },
--   managers = {
--     lazy = { ..lazy options }
--     langserv = { .. langserv options }
--   },
--   setup = { 'ui', 'editor' },
--   after = { ... }
-- }
-- setup.ui == lua/config/setup/ui.lua
-- ui.load()
-- editor.load()
